import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--bg)]">
      <nav className="sticky top-0 z-50 flex items-center justify-between px-4 sm:px-8 md:px-12 h-14 border-b border-[var(--border)] bg-[rgba(8,8,8,0.96)] backdrop-blur-xl">
        <Link href="/" className="flex items-center gap-2 text-[15px] font-extrabold tracking-tight">
          <svg width="16" height="16" viewBox="0 0 20 20" fill="none" className="text-[var(--green)]">
            <polyline points="1,14 6,8 10,11 15,4 19,7" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          SniperVision AI
        </Link>
        <Link href="/" className="text-[12px] text-[#777] hover:text-white transition-colors">← Back to Home</Link>
      </nav>

      <div className="max-w-[720px] mx-auto px-4 sm:px-8 py-16">
        <div className="mb-10">
          <div className="text-[10px] font-mono-tv font-bold text-[#555] tracking-widest mb-3">LEGAL</div>
          <h1 className="text-[clamp(28px,4vw,42px)] font-black tracking-tight mb-2">Terms of Service</h1>
          <p className="text-[12px] text-[#555]">Last updated: April 2026</p>
        </div>

        <div className="flex flex-col gap-8 text-[13px] text-[#aaa] leading-relaxed">

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using SniperVision AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">2. Educational Purpose Only</h2>
            <p className="mb-3">SniperVision AI is an educational tool designed to assist traders in analysing charts and learning about technical analysis. <strong className="text-white">The Service does not constitute financial advice, investment advice, or trading recommendations.</strong></p>
            <p>All analysis generated by the AI is for educational and informational purposes only. You should not make financial decisions based solely on the output of this Service.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">3. No Guarantee of Accuracy</h2>
            <p className="mb-3">AI-generated analysis is not 100% accurate. Markets are inherently unpredictable and past performance is not indicative of future results. SniperVision AI makes no representations or warranties regarding the accuracy, completeness, or reliability of any analysis provided.</p>
            <p>You acknowledge that trading involves substantial risk of loss and that you may lose some or all of your invested capital.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">4. User Responsibilities</h2>
            <ul className="flex flex-col gap-2 mt-2">
              {[
                'You are solely responsible for all trading decisions you make',
                'You must be of legal age in your jurisdiction to use financial tools',
                'You agree not to use the Service for any unlawful purpose',
                'You are responsible for maintaining the security of your account credentials',
                'You agree not to share, resell, or redistribute analysis outputs commercially',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-[var(--green)] mt-0.5 flex-shrink-0">•</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">5. Subscription and Billing</h2>
            <p className="mb-3">Subscription plans are billed monthly. You may cancel your subscription at any time. Refunds are provided at our discretion for unused periods within 7 days of billing. Daily analysis limits reset at midnight UTC.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">6. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, SniperVision AI and its operators shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to trading losses, loss of profits, or loss of data.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">7. Intellectual Property</h2>
            <p>All content, branding, and technology within the Service is owned by SniperVision AI. You may not copy, modify, or distribute any part of the Service without prior written consent.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">8. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms. We will notify users of material changes via email or in-app notification.</p>
          </section>

          <section>
            <h2 className="text-[16px] font-bold text-white mb-2">9. Contact</h2>
            <p>For any questions regarding these Terms, please contact us at <a href="mailto:support@tradevisionsai.com" className="text-[var(--green)] hover:underline">support@tradevisionsai.com</a>.</p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-[var(--border)] flex gap-4 text-[12px]">
          <Link href="/privacy" className="text-[var(--green)] hover:underline">Privacy Policy →</Link>
          <Link href="/" className="text-[#777] hover:text-white transition-colors">← Home</Link>
        </div>
      </div>
    </div>
  )
}
